sudo: required
language: generic

services:
	- docker-react

before_install:
	- docker build -t tiennv000/docker-react -f Dockerfile.dev .

script:
	- docker run -e CI=true tiennv000/docker-react npm run test

